// 50 lines each. All playful/teasing for friends messing around, not
// genuinely mean-spirited content or anything targeting protected traits.

const INSULTS = [
  "you're the human version of a buffering wheel.",
  "you have the energy of a phone at 1% brightness.",
  "you're proof that autocorrect isn't the only thing that makes mistakes.",
  "you bring everyone so much joy... when you leave the room.",
  "your Wi-Fi signal has more bars than your personality.",
  "you're like a software update — nobody asked for you and you slow everything down.",
  "you're the reason shampoo bottles have instructions.",
  "you have the charisma of a loading screen stuck at 99%.",
  "you're like a plot twist nobody wanted.",
  "if common sense was a class, you'd need summer school.",
  "you're about as sharp as a bowling ball.",
  "you're the human equivalent of a typo.",
  "your brain has more tabs open than actual RAM.",
  "you peaked the day you were born, and it's been downhill since.",
  "you're the reason group projects have trust issues.",
  "you have main character energy but side character screen time.",
  "you're like a cloud — the moment you disappear, the day gets better.",
  "you're proof evolution can go backwards.",
  "you're the human version of a CAPTCHA nobody can solve.",
  "you've got the decision-making skills of a Roomba stuck in a corner.",
  "you're like a pop-up ad — unwanted and impossible to close fast enough.",
  "you're the human version of a dropped call.",
  "you have the subtlety of a fire alarm at 3am.",
  "you're the reason instructions come with pictures now.",
  "you're like a broken pencil — completely pointless.",
  "you're the human version of 'please hold.'",
  "your opinions have the weight of a participation trophy.",
  "you're like autocorrect on a bad day — always wrong, always confident.",
  "you're the human version of a 404 error.",
  "you've got the timing of a smoke detector during a shower.",
  "you're like a printer — never working when it actually matters.",
  "you're the reason 'read the room' had to be invented.",
  "you have main-villain confidence with side-character results.",
  "you're like a group chat notification nobody wanted.",
  "you're the human version of expired milk — nobody notices until it's too late.",
  "you're the reason spellcheck exists.",
  "you're like a low battery warning — annoying and always at the worst time.",
  "you have the aim of a Nerf gun in the dark.",
  "you're the human version of a buffering video call.",
  "you're like a mosquito at 2am — small but somehow ruining everything.",
  "you're the reason parental controls exist.",
  "you're like a text left on read — expected, honestly.",
  "you've got the memory of an incognito tab.",
  "you're the human version of a spinning wheel of death.",
  "you're like a discount version of everyone else's ideas.",
  "you're the reason 'terms and conditions' got longer.",
  "you're like a dial-up connection in a fiber-optic world.",
  "you're the human version of a participation award.",
  "you have the presence of a muted mic on an important call.",
  "you're like a screen door on a submarine — completely pointless.",
];

const RIZZ = [
  "are you a Wi-Fi signal? because I'm feeling a real connection.",
  "if being fine was a crime you'd be doing life.",
  "are you a parking ticket? because you've got fine written all over you.",
  "is your name Google? because you're everything I've been searching for.",
  "you must be a magician, because whenever I look at you everyone else disappears.",
  "are you a camera? because every time I see you, I smile.",
  "do you have a map? I keep getting lost in your eyes.",
  "if I could rearrange the alphabet I'd put U and I together.",
  "are you made of copper and tellurium? because you're Cu-Te.",
  "is it hot in here, or is it just you?",
  "are you a time traveler? because I can totally see you in my future.",
  "excuse me, I think you dropped something: my jaw.",
  "are you French? because Eiffel for you.",
  "do you believe in love at first sight, or should I walk by again?",
  "are you a loan? because you've got my interest.",
  "are you a campfire? because you're hot and I want s'more.",
  "is your dad a boxer? because you're a knockout.",
  "are you an interior decorator? because when I saw you, the room became beautiful.",
  "are you a keyboard? because you're just my type.",
  "if you were a vegetable you'd be a cute-cumber.",
  "are you a bank loan? because you have my interest and now I'm losing sleep.",
  "do you have a Band-Aid? because I just scraped my knee falling for you.",
  "are you Wi-Fi? because I'm really feeling a connection.",
  "are you a parking spot? because you're hard to find and totally worth it.",
  "is your name Wi-Fi? because I'm really feeling a connection right now.",
  "are you an angel? because heaven's missing one.",
  "are you a star? because your beauty lights up the sky.",
  "is your body from McDonald's? because I'm loving it.",
  "are you a snowflake? because you're one of a kind.",
  "are you a broom? because you just swept me off my feet.",
  "do you have a sunburn, or are you always this hot?",
  "are you a fruit? because honeydew you know how cute you are?",
  "are you a triangle? because you're the only point I need.",
  "if you were words on a page you'd be fine print.",
  "are you a volcano? because I lava you.",
  "are you an artist? because you drew me in right away.",
  "are you gravity? because you're pulling me in.",
  "is your name Chapstick? because you're da balm.",
  "are you the sun? because you brighten up my whole day.",
  "are you a puzzle? because I'm stuck on you.",
  "is it just me, or did we just click?",
  "are you a compass? because I'd be lost without you.",
  "do you like raisins? how about a date instead?",
  "are you a library book? because I'm checking you out.",
  "are you a candle? because you just lit up the room.",
  "are you an angle? because you're acute one.",
  "are you a ghost? because you just haunted my thoughts all day.",
  "do you have a name, or can I just call you mine?",
  "are you the ocean? because I'm lost in your eyes.",
  "is your name Netflix? because I could watch you for hours.",
  "are you a shooting star? because my wish just came true.",
];

const ROASTS = [
  "you're the reason the gene pool needs a lifeguard.",
  "I'd explain it to you but I left my crayons at home.",
  "you have something on your chin... no, the third one down.",
  "you're not stupid, you just have bad luck thinking.",
  "if I wanted to kill time, I'd just watch you try to make a decision.",
  "you're the human equivalent of a participation trophy.",
  "I've seen better conversation from a vending machine.",
  "you have the perfect face for radio.",
  "if laziness were a sport, you'd still find a way to lose.",
  "you're not the dumbest person alive, but you better hope they don't die.",
  "your secrets are always safe with me — I never even listen when you talk.",
  "you're like a cloud — when you disappear, it's a beautiful day.",
  "I'm not saying you're slow, but you'd lose a race to a snail on vacation.",
  "you bring everyone so much joy... when you finally leave.",
  "you're proof that even evolution takes a day off sometimes.",
  "somewhere out there a tree is producing oxygen for you — you owe it an apology.",
  "you're the reason the manual says 'do not eat.'",
  "I'd agree with you, but then we'd both be wrong.",
  "you're like a software bug nobody bothered to fix.",
  "you have such a unique perspective — completely wrong, but unique.",
  "your GPS must hate you, always sending you nowhere in life.",
  "you're the human version of a typo in an important document.",
  "you're not the sharpest tool in the shed, more like the shed itself.",
  "you're living proof that not every seed grows into a tree.",
  "you're the reason instructions have pictures now.",
  "you're like a broken clock — wrong all the time, not just twice a day.",
  "if ignorance is bliss, you must be the happiest person alive.",
  "you're the human version of a spam email.",
  "you talk a big game for someone who folds this easily.",
  "you're the reason 'common sense isn't common' is a saying.",
  "you're like a decaf coffee — all the disappointment, none of the benefits.",
  "you have main-character delusion with extra-in-the-background results.",
  "you're the reason group chats need a mute button.",
  "you're like a discount version of someone with actual ideas.",
  "you're proof that confidence and competence aren't the same thing.",
  "you're the human version of a buffering circle.",
  "you're the reason the 'skip intro' button exists — nobody wants your backstory.",
  "you have the wit of a fortune cookie that ran out of fortunes.",
  "you're like a printer jam — completely avoidable, endlessly frustrating.",
  "you're the human version of an out-of-office reply.",
  "you're proof that being first doesn't mean being right.",
  "you're the reason parental advisory stickers exist — just not for the reason you'd hope.",
  "you're like a pop quiz — nobody's ready and everyone's disappointed.",
  "you talk like you're reading off cue cards someone else wrote wrong.",
  "you're the human version of a 'terms and conditions' nobody reads.",
  "you're the reason autocorrect gave up trying.",
  "you're like a rerun — seen it before, still not interested.",
  "you're the human version of a low battery notification.",
  "you're proof that loud and right aren't the same thing.",
  "you're the reason spellcheck needs a coffee break.",
];

const COMPLIMENTS = [
  "you light up every room you walk into.",
  "your ideas always make me think differently — in a good way.",
  "you have this calm energy that makes people feel safe around you.",
  "you're one of the most genuine people I know.",
  "you make hard days feel a little lighter.",
  "you have a way of noticing things others miss.",
  "your patience with people is honestly impressive.",
  "you make everyone around you better just by being there.",
  "you're the kind of friend people actually count on.",
  "your sense of humor makes even bad days bearable.",
  "you have a really rare kind of honesty.",
  "you always know exactly what to say.",
  "your creativity never stops surprising me.",
  "you're way stronger than you give yourself credit for.",
  "people trust you because you actually follow through.",
  "you make people feel heard, not just listened to.",
  "your energy is genuinely contagious.",
  "you have great taste — in everything, honestly.",
  "you're one of the few people who actually keeps their word.",
  "you handle pressure better than almost anyone I know.",
  "you have a gift for making people feel welcome.",
  "your work ethic is honestly inspiring.",
  "you're so easy to talk to, it's kind of a superpower.",
  "you always find the silver lining without ignoring the problem.",
  "you're incredibly thoughtful in ways people don't always notice.",
  "you make ordinary moments feel special.",
  "you have this quiet confidence that's really admirable.",
  "you're one of the most loyal people I've ever met.",
  "you always ask the right questions.",
  "you have an eye for detail most people don't bother with.",
  "your kindness is the kind that doesn't need an audience.",
  "you make people feel like their opinions actually matter.",
  "you're really good at making people laugh without even trying.",
  "you carry yourself with more grace than you realize.",
  "you're the person people go to when things get hard.",
  "you have a way of turning chaos into calm.",
  "your perspective on things is genuinely refreshing.",
  "you're incredibly self-aware, and that's rare.",
  "you make people want to be better just by example.",
  "you're someone people genuinely enjoy being around.",
  "you have this quiet strength people don't always see at first.",
  "you're really good at reading a room.",
  "your generosity never goes unnoticed, even when you think it does.",
  "you have a talent for making complicated things simple.",
  "you're consistently one of the most reliable people I know.",
  "you bring out the best in the people around you.",
  "your curiosity about the world is honestly inspiring.",
  "you're way more capable than you give yourself credit for.",
  "you have a rare ability to stay grounded under pressure.",
  "you're just a genuinely good person, and it shows.",
];

module.exports = { INSULTS, RIZZ, ROASTS, COMPLIMENTS };
